[package]
name = "protocols"
version = "0.1.0"
authors = ["Hui Zhu <teawater@hyper.sh>"]
edition = "2018"

[dependencies]
ttrpc = { git="https://github.com/lifupan/ttrpc-rust", branch="vsock" }
protobuf = "2.6.1"
futures = "0.1.27"
